services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: YouDontWannaIt
      MYSQL_USER: sweeftUser
      MYSQL_PASSWORD: sweeftPassword
      MYSQL_DATABASE: sweeft_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  app: 
    build:
      context: .
      dockerfile: dockerFile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    env_file: 
      - .env 
    working_dir: /app
    command: |
      sh -c "
        until mysqladmin ping -h mysql --silent; do
          echo 'Waiting for MySQL to be ready...';
          sleep 1;
        done;
        npx prisma db push;
        npm run start:prod"
    depends_on:
      mysql:
        condition: service_healthy